#
# Copyright (C) 2024 The Android Open Source Project
# Copyright (C) 2024 SebaUbuntu's TWRP device tree generator
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/sts/a05bd
BOARD_VENDOR := sts
BOARD_DEVICE := a05bd
BOARD_HAS_NFC := false
BOARD_USES_NFC := false
TARGET_USES_NFC := false
TARGET_BUILD_64BIT := true
TARGET_BOARD_SUFFIX := _64
TARGET_OTA_ASSERT_DEVICE := TAB-A05-BD,a05bd,lineage_a05bd
BOARD_HAS_MTK_HARDWARE := true
BOARD_USES_MTK_HARDWARE := true
MTK_HARDWARE := true
ENABLE_CPUSETS := true
ENABLE_SCHEDBOOST := true
AB_OTA_UPDATER := false

# For building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := 
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := generic
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := generic
TARGET_CPU_ABI_LIST_64_BIT := $(TARGET_CPU_ABI)
TARGET_CPU_ABI_LIST_32_BIT := $(TARGET_2ND_CPU_ABI),$(TARGET_2ND_CPU_ABI2)
TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI_LIST_64_BIT),$(TARGET_CPU_ABI_LIST_32_BIT)
TARGET_IS_64_BIT := true
TARGET_USES_64_BIT_BINDER := true
TARGET_USES_32_BIT_BINDER := true

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := a05bd
TARGET_NO_BOOTLOADER := true

# Display
DEVICE_RESOLUTION := 1920x1200
TARGET_SCREEN_DENSITY := 213
TARGET_SCREEN_HEIGHT := 1920
TARGET_SCREEN_WIDTH := 1200

# Kernel
BOARD_BOOTIMG_HEADER_VERSION := 1
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_CMDLINE += "androidboot.selinux=permissive"
BOARD_KERNEL_CMDLINE += "androidboot.vbmeta.avb_version=1.1"
BOARD_KERNEL_CMDLINE += "androidboot.vbmeta.device_state=unlocked"
BOARD_KERNEL_CMDLINE += "androidboot.vbmeta.invalidate_on_error=no"
BOARD_KERNEL_CMDLINE += "androidboot.veritymode=ignore_corruption"
BOARD_KERNEL_CMDLINE += "bootopt=64S3,32N2,64N2"
BOARD_KERNEL_CMDLINE += "androidboot.atm=disabled"
BOARD_KERNEL_CMDLINE += "androidboot.meta_log_disable=0"
BOARD_KERNEL_CMDLINE += "androidboot.dtbo_idx=0"
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x14f88000
BOARD_KERNEL_TAGS_OFFSET := 0x13f88000
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_KERNEL_IMAGE_NAME := Image
BOARD_KERNEL_SEPARATED_DTBO := true
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_CONFIG := a05bd_defconfig
TARGET_KERNEL_SOURCE := kernel/sts/a05bd
TARGET_KERNEL_CROSS_COMPILE_PREFIX := aarch64-linux-android-
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop
DEVICE_MATRIX_FILE   := $(DEVICE_PATH)/recovery/root/vendor/compatibility_matrix.xml
DEVICE_MANIFEST_FILE := $(DEVICE_PATH)/recovery/root/vendor/manifest.xml

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img
BOARD_KERNEL_SEPARATED_DTBO := 
endif

# Partitions
BOARD_BUILD_SYSTEM_ROOT_IMAGE := true
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_USES_REMOUNT := true
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1413480448
TARGET_COPY_OUT_VENDOR := vendor


# Platform
TARGET_BOARD_PLATFORM := mt8168
TARGET_BOARD_PLATFORM_GPU := Mali-G52 MP1

# Recovery
BOARD_INCLUDE_RECOVERY_DTBO := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
LZMA_RAMDISK_TARGETS := recovery

# Verified Boot
BOARD_AVB_ENABLE := true

# OS
PLATFORM_SECURITY_PATCH := 2021-06-05
VENDOR_SECURITY_PATCH := 2021-06-05
PLATFORM_VERSION := 9.0.0
BOARD_OS_VERSION := 9.0.0
RECOVERY_SDCARD_ON_DATA := true
TW_INCLUDE_CRYPTO := true

# TWRP Configuration
TW_THEME := landscape_hdpi
TW_ROTATION := 270
TW_EXTRA_LANGUAGES := false
TW_DEFAULT_LANGUAGE := ja
TW_SCREEN_BLANK_ON_BOOT := true
TW_USE_EXTERNAL_STORAGE := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_EXCLUDE_LPTOOLS := true
TW_EXCLUDE_LPDUMP := true
TW_USE_TOOLBOX := true
TW_EXCLUDE_BASH := true
TW_EXCLUDE_TZDATA := true
TW_EXCLUDE_NANO := true 
TW_EXCLUDE_TWRPAPP := true
TW_EXCLUDE_PYTHON := true
TW_EXCLUDE_SUPERSU := true
TW_EXCLUDE_NTFS_3G := true
TW_INCLUDE_FB2PNG := false
TW_INCLUDE_DUMLOCK := false
TW_INCLUDE_INJECTTWRP := false
TW_NO_HAPTICS := true
TWRP_INCLUDE_LOGCAT := false
TW_DEVICE_VERSION := $(shell date -u +" %F")
RECOVERY_TOUCHSCREEN_SWAP_Y := true
RECOVERY_TOUCHSCREEN_FLIP_XY := true

